import logo from '../assets/logo.svg'
import bell from '../assets/icons/bell.svg'
import mail from '../assets/icons/mail.svg'
import account from '../assets/icons/account.svg'
import burgermenu from '../assets/icons/burgermenu.svg'
import telegram from '../assets/icons/telegram.svg'
import instagram from '../assets/icons/instagram.svg'
import facebook from '../assets/icons/facebook.svg'
import envelope from '../assets/icons/envelope.svg'
import phone from '../assets/icons/phone.svg'
import map_pin from '../assets/icons/map-pin.svg'
import circle_dollar from '../assets/icons/circle-dollar.svg'
import clock from '../assets/icons/clock.svg'
import arrow_right from '../assets/icons/arrow_right.svg'
import arrow_left from '../assets/icons/arrow_left.svg'
import arrow_down from '../assets/icons/arrow_down.svg'
import card_img from '../assets/img/card_img.jpg'
import selection_img from '../assets/img/selection_img.png'
import map_img from '../assets/img/map_img.png'
// galery
import img01 from '../assets/img/img01.png'
import img02 from '../assets/img/img02.png'
import img03 from '../assets/img/img03.png'
import img04 from '../assets/img/img04.png'
import img05 from '../assets/img/img05.png'
import award_image from '../assets/img/award_img.png'
// brands
import flows from '../assets/brands/flows.svg'
import monobank from '../assets/brands/monobank.svg'
import varus from '../assets/brands/Varus.svg'
import visa from '../assets/brands/visa.svg'
// reviews
import review01 from '../assets/img/review01.jpg'
import review02 from '../assets/img/review02.jpg'
import review03 from '../assets/img/review03.jpg'
// about
import about_img01 from '../assets/img/about_img01.png'
import about_img02 from '../assets/img/about_img02.png'
import about_img03 from '../assets/img/about_img03.png'
import decoration_bg from '../assets/img/decoration_bg.svg'
import decoration_bg2 from '../assets/img/decoration_bg2.svg'
import img_card_about01 from '../assets/img/img_card_about01.png'
import img_card_about_mobile01 from '../assets/img/img_card_about_mobile01.png'
import img_card_about02 from '../assets/img/img_card_about02.png'
import img_card_about_mobile02 from '../assets/img/img_card_about_mobile02.png'
import img_card_about03 from '../assets/img/img_card_about03.png'
import img_card_about_mobile03 from '../assets/img/img_card_about_mobile03.png'
// services
import services_img01 from '../assets/img/services_img01.png'
import services_img02 from '../assets/img/services_img02.png'
import services_img03 from '../assets/img/services_img03.png'
import services_img_mobile01 from '../assets/img/services_img_mobile01.png'
import services_img_mobile02 from '../assets/img/services_img_mobile02.png'
import services_img_mobile03 from '../assets/img/services_img_mobile03.png'
import services_img from '../assets/img/services_img.svg'
import single_img from '../assets/img/single_img.png'
import single_img_mobile from '../assets/img/single_img_mobile.png'
import review_img from '../assets/img/review_img.png'

export { logo, bell, mail, account, burgermenu, telegram, instagram, facebook, envelope, phone, card_img, map_pin, circle_dollar, clock, selection_img, img01, img02, img03, img04, img05, flows, monobank, varus, visa, award_image, review01, review02, review03, about_img01, about_img02, about_img03, decoration_bg, decoration_bg2, img_card_about01, img_card_about02, img_card_about03, img_card_about_mobile01, arrow_right, img_card_about_mobile02, img_card_about_mobile03, arrow_down, services_img01, services_img02, services_img03, services_img_mobile01, services_img_mobile02, services_img_mobile03, services_img, map_img, single_img, single_img_mobile, arrow_left, review_img }
